### ISSUE TITLE
Is it possible to automatically perform sort on save?

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [1nVitr0/plugin-vscode-blocksort#24]
Is it possible to configure this extension to automatically sort certain blocks of code? I have blocks of code that consist of large key-value pairs. Consider the following:

```
// Please keep this block sorted to improve readability
const someObject = {
  KeyC: 'foo',
  KeyA: 'bar',
  KeyB: 'baz',
  [...]
};
```

Instead of manually sorting the block every time I change its content it would be nice if the extension would do that automatically. An inline comment could be used to tell the extension what to do:

```
/* ext.1nVitr0.blocksort: auto-sort-block */
const someObject = {
  KeyA: 'bar',
  KeyB: 'baz',
  KeyC: 'foo',
  [...]
};
```

Now every time I change one of the keys and press "save" the block would be sorted automatically.

**Comment by 1nVitr0** [comment]
Sorry for the late response.

That does sound like a great idea and shouldn't be that hard to implement. I will have to look into how to best support the feature with blocks not beginning in the same line (such as c-style switch-case statements). I'll definitely have an implementation ready by the end of the week.

**Comment by 1nVitr0** [comment]
for reference, corresponding branch is [feature/#24/sort-on-save](https://github.com/1nVitr0/plugin-vscode-blocksort/compare/develop.../feature/%2324%2Fsort-on-save).

**Comment by 1nVitr0** [comment]
@centigrade-thomas-becker Just to let you know, I just released the updated version. Following the newish approach by vscode to use `codeActionsOnSave` you will have to extend your `settings.json` for this to work:

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.blocksort": true
  }
}
```

This should enable you to use the `@blocksort` marker anywhere in your code to make the following block auto-sort on save:

```js
// @blocksort asc
switch(value) {
  case 1:
    return 1;
  case 2:
    return 2;
  default:
    return 2;
}
```

You can use it by itself (`// @bocksort`), with an order specified (`// @blocksort asc`) or with an additional depth (`// @blocksort desc 9`).

I tried to keep it reasonably performant, let me know if you have any issues. I will follow up with some automated tests to verify it working.

**Comment by 1nVitr0** [comment]
It definitely still has some issues with `yaml` files, I hope the testst will iron those out...

**Comment by 1nVitr0** [comment]
@centigrade-thomas-becker Alright, now it should be fully supported. You can also use the formatter "Block Sort", although I highly recommend using Code Actions. Due to the extension being language-agnostic it will now be always active to provide code actions, code lenses and the formatter. This is unavoidable. If you notice any performance issues feel free to open another issue.

**Comment by centigrade-thomas-becker** [comment]
Thanks for your work. I have added the new "@blocksort" annotation in a few places and it seems to work as intended 👍 

I will keep an eye on these blocks and inform you if I see anything suspicious.
