### ISSUE TITLE
[Feature Request] Have more // @blocksort per file 

### ISSUE THREAD

**Issue by ShawnBrew** [1nVitr0/plugin-vscode-blocksort#37]
I'd like to say thanks for making this Sort extension. It works great. I think it would be a nice feature to have many // @blocksort in a single file at the same level of indentation but be able to provide different depths.

**Comment by 1nVitr0** [comment]
@ShawnBrew Glad you enjoy it!

This should already be supported, although I did spot some issues when trying that out. I won't bother you with the technicalities, but when a bested block with a `@blocksort` marker is *not* the first in its respective list, it gets overridden by the outer block sort.

I will extend the tests for this and hopefully have a fix ready by the end of the week.

Thanks for letting me know!

**Comment by 1nVitr0** [comment]
@ShawnBrew Multiple nested `@blocksort` markers are now supported with the next release.

It was a bit more complicated than I thought, so if you have any problems feel free open another issue, or add a message to this one.
