### ISSUE TITLE
"Sort blocks ascending" shuffles things around but doesn't seem to actually sort them

### ISSUE THREAD

**Issue by axefrog** [1nVitr0/plugin-vscode-blocksort#45]
Hi, I was excited to see your extension listed in the marketplace and I quickly dived in to give it a go. Unfortunately the sorting algorithm doesn't seem to work correctly. I tested it on a file full of abstract classes, hoping to sort them alphabetically, but the "sorted" result didn't appear to be sorted on any obvious criteria, as none of the tokens in the line starting each block seemed to be a basis for the new sort order after I ran the command. I then tested it out on a reduced example where I removed the body of each class declaration, and the sorted result was still erroneous. I've included my reduced example below:

```ts
export abstract class BaseTask extends BaseRuntimeObject<'task'> implements Task {}
export abstract class BaseClient extends BaseRuntimeObject<'client'> implements Client {}
export abstract class BaseAgent extends BaseRuntimeObject<'agent'> implements Agent {}
export abstract class BaseTraversalSink extends BaseRuntimeObject<'sink:traverse'> implements TraversalSink {}
export abstract class BaseReaderSink<T> extends BaseRuntimeObject<'sink:read'> implements ReaderSink<T> {}
export abstract class BaseWriterSink<T> extends BaseRuntimeObject<'sink:write'> implements WriterSink<T> {}
export abstract class BaseExecutionSink<T> extends BaseRuntimeObject<'sink:execute'> implements ExecutionSink<T> {}
```

1. Select all
2. Command: "Sort: Sort Blocks Ascending"
3. Output:

```ts
export abstract class BaseAgent extends BaseRuntimeObject<'agent'> implements Agent {}
export abstract class BaseClient extends BaseRuntimeObject<'client'> implements Client {}
export abstract class BaseReaderSink<T> extends BaseRuntimeObject<'sink:read'> implements ReaderSink<T> {}
export abstract class BaseWriterSink<T> extends BaseRuntimeObject<'sink:write'> implements WriterSink<T> {}
export abstract class BaseExecutionSink<T> extends BaseRuntimeObject<'sink:execute'> implements ExecutionSink<T> {}

export abstract class BaseTask extends BaseRuntimeObject<'task'> implements Task {}
export abstract class BaseTraversalSink extends BaseRuntimeObject<'sink:traverse'> implements TraversalSink {}
```

You can see that the class names are not actually in order, and that there is no pattern that is common to all lines as the apparent basis for sorting.

Also I'm not sure why an extraneous line has been inserted in the middle. I am assuming that the sorting algorithm has a bug, and that the blank line's position is a side effect of the bug.

**Comment by 1nVitr0** [comment]
Thanks for the report! That looks like the algorithm for detecting inline-blocks has some error (I assume due to the `<>` generics). The algorithm is language-agnostic, so it might have some issues with language specific tokens, such as `<>`.

The result looks to me, like the sorting grouped all lines with `<>` together and then sorted the blocks. This is of course not intended, I'll fix the issue as soon as possible.

**Comment by 1nVitr0** [comment]
Yes, this is definitely an issue with `<>`. The false detection is due to compatibility with XML-like languages, where blocks are started with `<...>` and ended with `</...>``.

This was implemented wrong by me anyway, as HTML supports self closing tags such as `<br>`.

**Comment by axefrog** [comment]
As a fallback option that the user could configure, maybe it's a good idea to allow simple indentation as a way to detect blocks? Could cover a lot of use cases that you wouldn't then have to think about.

**Comment by 1nVitr0** [comment]
If I remember correctly, I added folding markers  to supper c-like Syntax, where the `{` is in the next line.

I tried to avoid language specific Syntax as much as possible, to get around the issue of things like JSX in typescript files. But this is definitely a case where that backfired.

I'll have to work on the issue a little, as an intermediate fix I allowed users to override the default folding markers in #46.  You should be able to add the following setting:

```
"blocksort.foldingMarkers": {
    "start": "<", 
    "end": ">"
}
```

This is untested, I'm on my phone right now. Once it's deployed (and I have updated the VSCE token) there should be a corresponding comment unter the pull request #46

**Comment by 1nVitr0** [comment]
Wel taht didn't seem to work. Will look into it on the weekend

**Comment by 1nVitr0** [comment]
The above temporary fix seems to work. I will try to have a long term fix ready until next week

**Comment by 1nVitr0** [comment]
Feel free to make me reopen it if you have any issues ;)

**Comment by axefrog** [comment]
Great thanks for that. I'll give it another go and let you know if I have any issues.
