### ISSUE TITLE
Inline codelens and fixall issues in both Python and JS code

### ISSUE THREAD

**Issue by whardier** [1nVitr0/plugin-vscode-blocksort#60]
I can only seem to get fixall to operate at the root level with respect to javascript code:

Here you can see the codelens action and if the file is saved it will automatically sort.. zealously.
<img width="754" alt="image" src="https://user-images.githubusercontent.com/305301/204113233-d737e719-9a07-4252-9b9d-54597496b043.png">

Adding the indent just seems to break what is seen in the documentation as an option (indented block sorting).
<img width="757" alt="image" src="https://user-images.githubusercontent.com/305301/204113246-deb7a85f-66c5-4f13-8cb6-a514ec172b5f.png">

Nothing works with respect to python code/comments:
<img width="761" alt="image" src="https://user-images.githubusercontent.com/305301/204113403-e74b0ba9-b41c-4355-a1c0-92363c64368c.png">

I'm hoping to use blocksort with some large string arrays (all have commas at the end of the line).  When using block sort I have a hard time limiting the sort to the current indent level via the editor as well.

Just a heads up that recent vscode may have made some changes how the inline action tags work when indented or when using a comment prefixed with hash.

**Comment by 1nVitr0** [comment]
Looks to me like the comment detection is broken in python for some reason. Should be an easy fix. I might try to refactor the code soon for some massive performance improvements (hopefully)

**Comment by whardier** [comment]
Thanks.. I'm seeing this now however:

![image](https://user-images.githubusercontent.com/305301/205571820-2d405b23-6734-40c8-9a7a-d7d566b4ef91.png)

![image](https://user-images.githubusercontent.com/305301/205571946-1e7e2c74-ff49-47e0-8968-ac6f2be933bf.png)
