### ISSUE TITLE
Inconsistent result with line sort and block sort

### ISSUE THREAD

**Issue by freddo256** [1nVitr0/plugin-vscode-blocksort#71]
I noticed a few times block sort and line sort generate different result on special characters.

Line sort puts `_` before `:` while for block sort it's the other way around.

**Comment by 1nVitr0** [comment]
I can look into that, currently it simply sorts based on the byte value of the characters

**Comment by 1nVitr0** [comment]
Sorry for the delay. Should be fixed in the next update. It was due to `Sort Lines` using `localeCompare` instead of the `<` operator.

**Comment by 1nVitr0** [comment]
Update: I have now updated the release token, it was invalid... It has now been actually release
