### ISSUE TITLE
Support sorting TypeScript/JS objects involving arrow functions

### ISSUE THREAD

**Issue by feritarou** [1nVitr0/plugin-vscode-blocksort#76]
First of all, let me emphasize that I love the idea of this extension, thanks for the great work!!

To help improve it further, let me report this bug I discovered specifically for TS/JS code (haven't checked other languages):

The code below gets sorted correctly:
```ts
const demo1 = {
  some: 1,
  another: 2,
}
```
And also does this one:
```ts
const demo2 = {
  some: 1,
  another: function() { // using the shortcut notation `another() { ... }` also works
    return 2
  },
}
```

But replacing `another` with an arrow function:
```ts
const demo3 = {
  some: 1,
  another: () => {
    return 2
  },
}
```
makes the extension show an error message "Cannot destructure property 'hasContent'  of 'object null' as it is null."

Similarly, the variants below confuses the extension about the selection scope, so while it won't throw an error, it still doesn't sort the keys as it should:
```ts
const demo4 = {
  some: 1,
  another: () => 2,
}

const demo5 = {
  some: 1,
  another: myFunction({ object: (t: unknown) => 'prop' }),
}
```

**Comment by 1nVitr0** [comment]
Will release it together with #78 during this week. Though I did notice another issue with trailing commas. That doesn't directly affect arrow functions, so that will be part of the next release

**Comment by feritarou** [comment]
Thank you! Highly appreciated.

Aram Becker ***@***.***> schrieb am Mo., 8. Jan. 2024, 16:17:
