### ISSUE TITLE
Feature - Configuration property for custom sorting

### ISSUE THREAD

**Issue by SamuelFerreiraJimpisoft** [1nVitr0/plugin-vscode-blocksort#78]
First of all, great extension 💯 It really helps me out a lot 🎉 Big thank you for that 🙏 

It would be very nice if you could add a configuration to sort the properties in a custom order. 
For example I am working with Vue and I would like to sort the HTML properties like this:
```html
<component
  aaa
  bbb
  :aaa
  :bbb
  @aaa
  @bbb
/>
```

However the current sort only allows to be like this: 
```html
<component
  :aaa
  :bbb
  @aaa
  @bbb
  aaa
  bbb
/>
```

Maybe the configuration could be something like this:
```json
"blockSort.customAscendingSortOrder": "abcdefghijklmnopqrstuvwxyz:@"
```

**Comment by 1nVitr0** [comment]
Just release the update. Custom sort order is now supported by setting `customSortOrder` in `blocksort.collatorOptions`. Default with custom order would be:

```json
{
    "numeric": true,
    "caseFirst": "false",
    "sensitivity": "base",
    "customSortOrder": "abcdefghijklmnopqrstuvwxyz:@"
  }
```

You will face an issue with the `@` symbol that gets detected as a decorator. That means a `@` above another line will always stick to the line below. I didn't want to delay #76 any longer, so I release it without a fix for now. I'm not sure how to tackle this yet, hopefully it will be ready next week.

**Comment by pavelloz** [comment]
Hey @1nVitr0 

I started to get this message since last update (i assume its the one above):
![image](https://github.com/1nVitr0/plugin-vscode-blocksort/assets/546845/ce876429-34e8-401e-82b0-6522d73c7d48)

I tried everything i could think of to get rid of it, including reinstalling the extension, but no luck. Any advice?

**Comment by 1nVitr0** [comment]
I'll add a button on the next release that will fix it immediately. For now it should be enough either remove the setting `blocksort.enableNaturalSorting`.

It should also be possible to reset the setting when clicking on "Open Settings", or checking and unchecking the box there.

If that doesn't work, I'll temporarily remove the snippet that display the message

**Comment by 1nVitr0** [comment]
I have just removed the deprecation notice. If you did use natural sorting, it is now enabled by default. So there's actually nothing tp do there.

**Comment by SamuelFerreiraJimpisoft** [comment]
Thank you very much for this implementation 🙏 🎉 🚀

**Comment by 1nVitr0** [comment]
@SamuelFerreiraJimpisoft Thanks for the heads-up. I'm really busy atm, so it might take me a few weeks to get arount to this. Though I'm nozt sure how it could've broken...

**Comment by 1nVitr0** [comment]
@SamuelFerreiraJimpisoft Right, I found the issue. This is because the `@` prefix is parsed as a decorator which will "stick" to the line below and is ignored during sorting. `:` Has been working in my tests though. I will make the decorator detection only active for code languages and make the feature togglable in the settings.

**Comment by 1nVitr0** [comment]
@SamuelFerreiraJimpisoft Don't think a setting is necessary, I added per-language decorator definitions in #113 (currently for Java, TypeScript / JavaScript and Python which all use `@`). Feel free to open a new issue if custom sort ordering is still not working with the next update-

**Comment by SamuelFerreiraJimpisoft** [comment]
@1nVitr0 thank you for your feedback. Unfortunately it's still not working. Don't know if I did something wrong. 
As suggested, I opened and new issue, this one https://github.com/1nVitr0/plugin-vscode-blocksort/issues/114. Once again, thank you.
