### ISSUE TITLE
Block Sort sorts entire file instead of just selected lines

### ISSUE THREAD

**Issue by jze2** [1nVitr0/plugin-vscode-blocksort#97]
I tried to sort a file containing something like
```
data "vault_generic_secret" "test b" {
  path = ....
}

data "vault_generic_secret" "test a" {
  path = ....
}

data "vault_generic_secret" "example" {
  path = ....
}
```
Now even when I select only lines containing 
```
data "vault_generic_secret" "test a" {
  path = ....
}

data "vault_generic_secret" "example" {
  path = ....
}
```
it still sorts the whole file resulting in
```
data "vault_generic_secret" "example" {
  path = ....
}

data "vault_generic_secret" "test a" {
  path = ....
}

data "vault_generic_secret" "test b" {
  path = ....
}
```
but I expected
```
data "vault_generic_secret" "test b" {
  path = ....
}

data "vault_generic_secret" "example" {
  path = ....
}

data "vault_generic_secret" "test a" {
  path = ....
}
```

**Comment by 1nVitr0** [comment]
@jze2 At the moment, the extension does not support sorting multiple independent blocks simultaneously, you would have to select the inner part of each `data` block separately.

Alternatively you can make of the `@blocksort` code actions:

```r
# @blocksort asc
data "vault_generic_secret" "test b" {
  path = ....
}

# @blocksort asc
data "vault_generic_secret" "example" {
  path = ....
}

# @blocksort asc
data "vault_generic_secret" "test a" {
  path = ....
}
```

I will think about adding an additional command for sorting inner blocks without touching the surrounding elements. Though for language specific ordering of members and methods there is usually a language-specific extension.

**Comment by 1nVitr0** [comment]
@jze2 With the next release, there will be a  `Sort inner blocks` command, as well as support for only sorting inner blocks using the `@blocksort` marker:

```jsonc
// @blocksort inf:1
{
  "keep2": [
    "sort",
    "only",
    "inner",
    "values",
  ],
  "keep1": {
    "first": "level",
    "items": "will",
    "be": "kept",
  }
}
```

**Comment by jze2** [comment]
Well, I was thinking the more intuitive way would be to sort SELECTED area and distinguish what should be sorted by indentation of the first selected line.

**Comment by 1nVitr0** [comment]
@jze2 Sorry, aparrently I cannot read. You should already be able to do that,  the selection will only be expanded up to the next empty line (and there is an equal number of opening and closing `{[()]}` brackets). My best Guess is that you selected the line above `data "vault_generic_secret" "test a" {` as well?

```r
data "vault_generic_secret" "test b" {
  path = ....
}
>>> SELECTION START >>>
data "vault_generic_secret" "test a" {
  path = ....
}

data "vault_generic_secret" "example" {
  path = ....
}<<< SELECTION END <<<
```

instead of

```r
data "vault_generic_secret" "test b" {
  path = ....
}

>>> SELECTION START >>>data "vault_generic_secret" "test a" {
  path = ....
}

data "vault_generic_secret" "example" {
  path = ....
}<<< SELECTION END <<<
```

If you want absolutely no automatic expansion of your selection, you can set `blocksort.expandSelection` to `false` in your `settings.json`.
